export const NEW_COUPON_REQUEST = "NEW_COUPON_REQUEST";
export const NEW_COUPON_SUCCESS = "NEW_COUPON_SUCCESS";
export const NEW_COUPON_RESET = "NEW_COUPON_RESET";
export const NEW_COUPON_FAIL = "NEW_COUPON_FAIL";

export const ALL_COUPON_REQUEST = "ALL_COUPON_REQUEST";
export const ALL_COUPON_SUCCESS = "ALL_COUPON_SUCCESS";
export const ALL_COUPON_FAIL = "ALL_COUPON_FAIL";

export const COUPON_DETAILS_REQUEST = "COUPON_DETAILS_REQUEST";
export const COUPON_DETAILS_SUCCESS = "COUPON_DETAILS_SUCCESS";
export const COUPON_DETAILS_FAIL = "COUPON_DETAILS_FAIL";

export const UPDATE_COUPON_REQUEST = "UPDATE_COUPON_REQUEST";
export const UPDATE_COUPON_SUCCESS = "UPDATE_COUPON_SUCCESS";
export const UPDATE_COUPON_RESET = "UPDATE_COUPON_RESET";
export const UPDATE_COUPON_FAIL = "UPDATE_COUPON_FAIL";

export const DELETE_COUPON_REQUEST = "DELETE_COUPON_REQUEST";
export const DELETE_COUPON_SUCCESS = "DELETE_COUPON_SUCCESS";
export const DELETE_COUPON_RESET = "DELETE_COUPON_RESET";
export const DELETE_COUPON_FAIL = "DELETE_COUPON_FAIL";

export const LIMIT_COUPON_REQUEST = "LIMIT_COUPON_REQUEST";
export const LIMIT_COUPON_SUCCESS = "LIMIT_COUPON_SUCCESS";
export const LIMIT_COUPON_FAIL = "LIMIT_COUPON_FAIL";

export const REMOVE_COUPON_DETAILS = "REMOVE_COUPON_DETAILS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const COUPON_CODE = "COUPON_CODE";
export const EMPTY_COUPON_CODE = "EMPTY_COUPON_CODE";