export const GET_SHIPPING_REQUEST = "GET_SHIPPING_REQUEST";
export const GET_SHIPPING_SUCCESS = "GET_SHIPPING_SUCCESS";
export const GET_SHIPPING_FAIL = "GET_SHIPPING_FAIL";

export const NEW_SHIPPING_REQUEST = "NEW_SHIPPING_REQUEST";
export const NEW_SHIPPING_SUCCESS = "NEW_SHIPPING_SUCCESS";
export const NEW_SHIPPING_RESET = "NEW_SHIPPING_RESET";
export const NEW_SHIPPING_FAIL = "NEW_SHIPPING_FAIL";

export const UPDATE_SHIPPING_REQUEST = "UPDATE_SHIPPING_REQUEST";
export const UPDATE_SHIPPING_SUCCESS = "UPDATE_SHIPPING_SUCCESS";
export const UPDATE_SHIPPING_RESET = "UPDATE_SHIPPING_RESET";
export const UPDATE_SHIPPING_FAIL = "UPDATE_SHIPPING_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";